name: Convert STEP to STL

on:
  push:
    paths:
      - .github/workflows/foo.yaml
      - MK2/STEP/*.stp
      - MK2_EU/STEP/*.stp
      - MK2_UK/STEP/*.stp
  # pull_request:
  #   branches: [ "main" ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cadquery
    - name: Build file list
      run: |
        echo "why did nothing happen?"
        echo FILES=$(find MK2/STEP MK2_EU/STEP MK2_UK/STEP -name *.stp) | tee -a $GITHUB_ENV
    - name: Convert STEP to STL
      shell: python
      run: |
        import os
        import cadquery as cq

        for filename in os.listdir('.'):
          if filename.lower().endswith('.step') or filename.lower().endswith('.stp'):
            step_file = filename
            stl_file = os.path.splitext(filename)[0] + '.stl'

            print(f'Converting {step_file} to {stl_file}')

            result = cq.importers.importStep(step_file)
            # cq.exporters.export(result, stl_file)
    - name: Commit STL files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Convert STEP to STL
        branch: ${{ github.head_ref }}
